name: docker-image

on:
  push:
    branches: [ master, developer ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./distribution/x64/Dockerfile --tag bottowitzsch:$(date +%s)
